# Generated by Django 3.2 on 2021-06-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toys', '0005_auto_20210617_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.TextField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
