# Generated by Django 3.2 on 2021-06-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toys', '0008_order_productscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='Toys.Product'),
        ),
    ]
