# Generated by Django 3.2 on 2021-06-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toys', '0012_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
