# Generated by Django 3.2 on 2021-06-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toys', '0014_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='productscode',
            field=models.TextField(max_length=100),
        ),
    ]
