# Generated by Django 3.2 on 2021-06-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Toys', '0016_order_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
